# Generated by Django 3.2 on 2021-12-29 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='email',
        ),
        migrations.RemoveField(
            model_name='students',
            name='name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='password',
        ),
    ]
