# Generated by Django 3.2 on 2021-12-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_auto_20211229_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='session_year_id',
            new_name='session_year',
        ),
    ]
