# Generated by Django 3.2 on 2021-12-30 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_auto_20211229_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='staff_id',
            new_name='staff',
        ),
    ]
